name = "cors-proxy"
main = "src/worker.js"
compatibility_date = "2022-06-12"

[vars]
ALLOWED_HOSTS = "*"
REDIRECT_URL = "https://github.com/smash64-dev"

[env.production]
name = "cors-proxy"

[env.production.vars]
ALLOWED_HOSTS = "smash64.dev, smash64.online"
REDIRECT_URL = "https://github.com/smash64-dev"
