AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A collection of serverless functions to aid smash64-dev

Parameters:
  ApiSubdomain:
    Type: String
    Default: api
  OnlineDomain:
    Type: String
    Default: smash64.online
  Prefix:
    Type: String
    Default: serverless-tools
  ProxyHeader:
    Type: String
    Default: cf-connecting-ip
  Stage:
    Type: String
    Default: prod

Globals:
  Api:
    OpenApiVersion: 3.0.3
  Function:
    Handler: app.lambda_handler
    Runtime: python3.9
    Timeout: 7
    Environment:
      Variables:
        PROXY_HEADER: !Sub "${ProxyHeader}"

Resources:
  # api gateways
  OnlineDomainApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${ApiSubdomain}.${OnlineDomain}"
      Description: !Sub "Public REST API for ${OnlineDomain}"
      Cors:
        AllowHeaders: "'X-Forwarded-For'"
        AllowMethods: "'GET, POST'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      StageName: !Sub "${Stage}"

  # domain mapping - domain creation is handled outside this stack configuration
  OnlineDomainApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Sub "${ApiSubdomain}.${OnlineDomain}"
      RestApiId: !Ref OnlineDomainApi
      Stage: !Ref OnlineDomainApi.Stage

  # lambda layers
  KailleraPythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${Prefix}-lib-kaillera-py"
      Description: Minimal library to communicate with kaillera servers and okai p2p clients
      ContentUri: lib/python
    Metadata:
      BuildMethod: python3.9

  # lambda functions
  KailleraGetIPFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Prefix}-kaillera-get-ip"
      Description: Returns the IP address forwarded by the proxy service
      CodeUri: get-ip/src/
      Events:
        ServerCheck:
          Type: Api
          Properties:
            Path: /kaillera/get-ip
            Method: GET
            RestApiId:
              Ref: OnlineDomainApi

  KailleraP2PCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Prefix}-kaillera-p2p-check"
      Description: Checks if port forwarding is set up correctly for p2p
      CodeUri: p2p-check/src/
      Layers:
        - !Ref KailleraPythonLayer
      Events:
        ServerCheck:
          Type: Api
          Properties:
            Path: /kaillera/p2p-check
            Method: POST
            RestApiId:
              Ref: OnlineDomainApi

  KailleraServerCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Prefix}-kaillera-server-check"
      Description: Checks if a public kaillera server is running
      CodeUri: server-check/src/
      Layers:
        - !Ref KailleraPythonLayer
      Events:
        ServerCheck:
          Type: Api
          Properties:
            Path: /kaillera/server-check
            Method: POST
            RestApiId:
              Ref: OnlineDomainApi
