name: Publish workers to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy-aws-check:
    name: Publish connection-check via sam
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sam build --use-container --base-dir connection-check
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name smash64-dev-connection-check --s3-bucket ${{ secrets.AWS_S3_BUCKET }} --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }}
